-- MySQL Script generated by MySQL Workbench
-- Wed Mar  8 16:43:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petmall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petmall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petmall` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `petmall` ;

-- -----------------------------------------------------
-- Table `petmall`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petmall`.`member` (
  `id` VARCHAR(30) NOT NULL,
  `pw` VARCHAR(50) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `lv` INT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petmall`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petmall`.`cart` (
  `CART_NUM` INT NOT NULL AUTO_INCREMENT,
  `ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`CART_NUM`, `ID`),
  INDEX `fk_cart_member1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_cart_member1`
    FOREIGN KEY (`ID`)
    REFERENCES `petmall`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petmall`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petmall`.`product` (
  `PRODUCT_NUM` INT NOT NULL AUTO_INCREMENT,
  `SEARCH_TAG` VARCHAR(300) NULL DEFAULT NULL,
  `NAME` VARCHAR(150) NOT NULL,
  `PRICE` INT NOT NULL,
  `THUMBNAIL` VARCHAR(300) NULL DEFAULT NULL,
  `FREE_SHIPPING` INT NULL DEFAULT '0',
  `ON_DISCOUNT` INT NULL DEFAULT '0',
  `REG_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `content` VARCHAR(3000) NULL DEFAULT NULL,
  `review_count` INT NULL DEFAULT '0',
  PRIMARY KEY (`PRODUCT_NUM`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petmall`.`likeit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petmall`.`likeit` (
  `ID` VARCHAR(30) NOT NULL,
  `PRODUCT_NUM` INT NOT NULL,
  INDEX `fk_likeit_member_idx` (`ID` ASC) VISIBLE,
  INDEX `fk_likeit_product_idx` (`PRODUCT_NUM` ASC) VISIBLE,
  PRIMARY KEY (`ID`, `PRODUCT_NUM`),
  CONSTRAINT `fk_likeit_member`
    FOREIGN KEY (`ID`)
    REFERENCES `petmall`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likeit_product`
    FOREIGN KEY (`PRODUCT_NUM`)
    REFERENCES `petmall`.`product` (`PRODUCT_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petmall`.`order_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petmall`.`order_table` (
  `ORDER_NUM` INT NOT NULL AUTO_INCREMENT,
  `ID` VARCHAR(30) NOT NULL,
  `ORDER_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `TOTAL_PRICE` INT NOT NULL,
  `STATUS` INT NULL DEFAULT '0',
  PRIMARY KEY (`ORDER_NUM`, `ID`),
  INDEX `fk_order_member1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_order_table_member`
    FOREIGN KEY (`ID`)
    REFERENCES `petmall`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petmall`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petmall`.`review` (
  `REVIEW_NUM` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_NUM` INT NOT NULL,
  `ID` VARCHAR(30) NOT NULL,
  `CONTENT` VARCHAR(2000) NULL DEFAULT NULL,
  `REG_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`REVIEW_NUM`, `ID`, `PRODUCT_NUM`),
  INDEX `fk_review_product1_idx` (`PRODUCT_NUM` ASC) VISIBLE,
  INDEX `fk_review_member1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`PRODUCT_NUM`)
    REFERENCES `petmall`.`product` (`PRODUCT_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_member1`
    FOREIGN KEY (`ID`)
    REFERENCES `petmall`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6010
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petmall`.`cart_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petmall`.`cart_product` (
  `CART_NUM` INT NOT NULL,
  `PRODUCT_NUM` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  INDEX `fk_cart_has_product_product1_idx` (`PRODUCT_NUM` ASC) VISIBLE,
  INDEX `fk_cart_has_product_cart1_idx` (`CART_NUM` ASC) VISIBLE,
  PRIMARY KEY (`CART_NUM`),
  CONSTRAINT `fk_cart_has_product_cart1`
    FOREIGN KEY (`CART_NUM`)
    REFERENCES `petmall`.`cart` (`CART_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_has_product_product1`
    FOREIGN KEY (`PRODUCT_NUM`)
    REFERENCES `petmall`.`product` (`PRODUCT_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petmall`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petmall`.`order_detail` (
  `ORDER_NUM` INT NOT NULL,
  `PRODUCT_NUM` INT NOT NULL,
  `QUANTITY` INT NULL DEFAULT 1,
  INDEX `fk_order_detail_product1_idx` (`PRODUCT_NUM` ASC) VISIBLE,
  PRIMARY KEY (`ORDER_NUM`),
  CONSTRAINT `fk_order_detail_order_table`
    FOREIGN KEY (`ORDER_NUM`)
    REFERENCES `petmall`.`order_table` (`ORDER_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_detail_product`
    FOREIGN KEY (`PRODUCT_NUM`)
    REFERENCES `petmall`.`product` (`PRODUCT_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
